MattermostApiURL = "https://mattermost.example.com"
MattermostWsURL = "wss://mattermost.example.com"
AuthToken = "<token>"
TeamName = "myteam"

DisplayName = "MensaBot"

ChannelNameDebug = "mattermost-testing"

Favorites = ["burger"]

UseMafiasiMensa = true
CanteenIdToday = "canteen-0-10"
CanteenIdTomorrow = "canteen-99-10"
