MattermostApiURL = "https://mattermost.example.com"
MattermostWsURL = "wss://mattermost.example.com"
AuthToken = "<token>"
TeamName = "myteam"

DisplayName = "MensaBot"

ChannelNameDebug = "mattermost-testing"

Favorites = ["burger"]
