MattermostApiURL = "https://mattermost.example.com"
MattermostWsURL = "wss://mattermost.example.com"
UserEmail = "mensabot@mattermost.example.com"
UserPassword = "hunter2"
TeamName = "myteam"

DisplayName = "MensaBot"
MentionName = "@mensabot"

ChannelNameDebug = "mensabot_debug"
ChannelNameProduction = "mensabot"

Favorites = ["burger"]